# A string used to distinguish different Supabase projects on the same host. Defaults to the working directory name when running `supabase init`.
project_id = "toggl-api"

[api]
enabled = true
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API endpoints.
schemas = ["public", "graphql_public"]
# Extra schemas to add to the search_path of every request.
extra_search_path = ["public", "extensions"]
# The maximum number of rows returns from a view, table, or stored procedure. Limits payload size for accidental or malicious requests.
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 54322
# Port to use for the local database pooler URL.
pooler.port = 54329
# Port to use for the local database shadow URL.
shadow_port = 54320
# The database major version to use. This has to be the same as your remote database's.
major_version = 15

[db.settings]
# The path to your local database extensions.
# extension_path = "supabase/extensions"

[studio]
enabled = true
# Port to use for Supabase Studio.
port = 54323
# External URL of the API. Used for routing when setting up custom domains.
api_url = "http://127.0.0.1:54321"

[inbox]
# Port to use for the local inbox app.
port = 54324

[auth]
enabled = true
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used in emails.
site_url = "http://127.0.0.1:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post-authentication.
additional_redirect_urls = ["https://127.0.0.1:3000"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 (1 week).
jwt_expiry = 3600
# If disabled, the refresh token will never expire.
enable_refresh_token_rotation = true
# Allows refresh tokens to be reused after expiration, up to the specified interval in seconds.
refresh_token_reuse_interval = 10
# Allow/disallow new user signups to your project.
enable_signup = true
# Allow/disallow anonymous sign-ins to your project.
enable_anonymous_sign_in = false
# Allow/disallow magic link sign-ins to your project.
enable_magic_link = false
# Allow/disallow user password updates to your project.
enable_update_password_require_reauthentication = true

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email addresses.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false

[edge_runtime]
enabled = true
# Port to use for the local Edge Runtime.
port = 54325

[analytics]
enabled = true
port = 54327
# Configure one of the supported backends: `postgres`, `bigquery`.
backend = "postgres"